name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci

      - name: Check types
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run package

      - name: Test
        run: xvfb-run -a npm test
